### ISSUE TITLE
tabby.toggleTab() prevents from clicking previous active tab

### ISSUE THREAD

**Issue by roland-d** [cferdinandi/tabby#91] opened 2017-08-16 09:01 UTC
Title says it all :)

Steps to reproduce using the Unstructured list tabs:
1. Go to http://cferdinandi.github.io/tabby
2. In the Unstructured list click on Seasons
3. Tab now changes to seasons
4. Open the Console
5. Execute the code ```tabby.toggleTab('#tab2')```
6. The page now shows
```

Ice Cream

Chocolate, vanilla or strawberry?
```

7. Click on the Seasons tab
8. Nothing happens
9. Click on Superheroes
10. This works
11. Click on Seasons tab
12. Now this works as well

**Comment by cferdinandi** [comment] 2017-08-16 18:28
Ah, good catch! Can't commit to a completion date on this, but it's a fairly simple fix.

**Comment by roland-d** [comment] 2017-08-16 18:30
@cferdinandi Thank you for confirming this is an issue.

**Comment by roland-d** [comment] 2017-09-19 06:49
@cferdinandi Just wanting to give this a friendly nudge :) Since you said it is a fairly simple fix, is there anything I could put in as a quick fix? Thanks.

**Comment by dskvr** [comment] 2017-12-22 18:54
This is definitely a huge issue, sets `id` to `null`

**Comment by dskvr** [comment] 2017-12-22 18:59
For anyone that cares, I just commented out line *404* in the distribution file (didn't feel like recompiling) https://github.com/cferdinandi/tabby/blob/master/dist/js/tabby.js#L404.

I'm sure that breaks something else, but I haven't yet found an issue with it. Cheers.

**Comment by dskvr** [comment] 2017-12-22 19:03
For anyone that cares, the problem is at line [404](https://github.com/cferdinandi/tabby/blob/master/dist/js/tabby.js#L404)

I changed line 403 to the following:

```js
if ( tab && tab.getAttribute( 'data-tab-id' )) {
```
I don't understand the full scope of the script, but that doesn't seem to have any negative side effects. Cheers.

**Comment by cferdinandi** [comment] 2017-12-22 19:34
In its current form, the script removes the id to avoid page jumping, and then resets it when complete. If you comment out line 404, you break resetting the ID. Your check for the `data-tab-id` is the right way to address this for the moment, until I get a proper fix in place.

Sorry for the delay. Been heads down on my JavaScript guides and courses.

**Comment by cferdinandi** [comment] 2019-03-04 22:18
So like... a year and a half too late here, but a fix for this is coming tomorrow

**Comment by cferdinandi** [comment] 2019-03-05 03:33
Fixed with v12: https://github.com/cferdinandi/tabby/releases/tag/v12.0.0

**Closed by cferdinandi** 2019-03-05 03:33 UTC
Labels: bug
